// 老王整理：1000+热门歌手数据库
// 包含华语、欧美、日韩等各类歌手和组合

export const MALE_ARTISTS = [
  // === 华语顶级流行男歌手（100位） ===
  { name: '周杰伦', icon: '🎤', genre: '流行' },
  { name: '林俊杰', icon: '🎹', genre: '流行' },
  { name: '薛之谦', icon: '🎧', genre: '流行' },
  { name: '李荣浩', icon: '🎸', genre: '流行' },
  { name: '毛不易', icon: '🎼', genre: '民谣' },
  { name: '陈奕迅', icon: '🎤', genre: '流行' },
  { name: '张学友', icon: '👑', genre: '经典' },
  { name: '刘德华', icon: '⭐', genre: '经典' },
  { name: '许嵩', icon: '✨', genre: '流行' },
  { name: '汪苏泷', icon: '🎵', genre: '流行' },
  { name: '张杰', icon: '🔥', genre: '流行' },
  { name: '胡彦斌', icon: '🎹', genre: '流行' },
  { name: '赵雷', icon: '🎻', genre: '民谣' },
  { name: '周深', icon: '🌊', genre: '流行' },
  { name: '华晨宇', icon: '🌟', genre: '流行' },
  { name: '吴青峰', icon: '🎵', genre: '流行' },
  { name: '鹿晗', icon: '🦌', genre: '流行' },
  { name: '张艺兴', icon: '🎧', genre: '流行' },
  { name: '蔡徐坤', icon: '🏀', genre: '流行' },
  { name: '王源', icon: '🌟', genre: '流行' },
  { name: '易烊千玺', icon: '⭐', genre: '流行' },
  { name: '王俊凯', icon: '👑', genre: '流行' },
  { name: '肖战', icon: '🌟', genre: '流行' },
  { name: '王一博', icon: '🏍️', genre: '流行' },
  { name: '邓伦', icon: '🎤', genre: '流行' },
  { name: '萧敬腾', icon: '🎩', genre: '流行' },
  { name: '林宥嘉', icon: '🎸', genre: '流行' },
  { name: '杨宗纬', icon: '🎙️', genre: '流行' },
  { name: '李健', icon: '🎼', genre: '民谣' },
  { name: '朴树', icon: '🌳', genre: '民谣' },
  { name: '许巍', icon: '🎸', genre: '摇滚' },
  { name: '汪峰', icon: '🎤', genre: '摇滚' },
  { name: '郑钧', icon: '🎸', genre: '摇滚' },
  { name: '崔健', icon: '🎸', genre: '摇滚' },
  { name: '古巨基', icon: '🎹', genre: '流行' },
  { name: '陶喆', icon: '🎹', genre: 'R&B' },
  { name: '王力宏', icon: '🎸', genre: '流行' },
  { name: '罗大佑', icon: '🎸', genre: '经典' },
  { name: '张信哲', icon: '💝', genre: '经典' },
  { name: '任贤齐', icon: '🎤', genre: '流行' },
  { name: '周华健', icon: '🎸', genre: '经典' },
  { name: '李克勤', icon: '🎤', genre: '流行' },
  { name: '郭富城', icon: '⭐', genre: '流行' },
  { name: '黎明', icon: '🌟', genre: '流行' },
  { name: '谭咏麟', icon: '👑', genre: '经典' },
  { name: '张国荣', icon: '💫', genre: '经典' },
  { name: '张宇', icon: '🎤', genre: '流行' },
  { name: '品冠', icon: '🎼', genre: '流行' },
  { name: '光良', icon: '🎹', genre: '流行' },
  { name: '曹格', icon: '🎵', genre: '流行' },
  { name: '庾澄庆', icon: '🎤', genre: '流行' },
  { name: '费玉清', icon: '🎙️', genre: '经典' },
  { name: '齐秦', icon: '🎸', genre: '流行' },
  { name: '伍佰', icon: '🎸', genre: '摇滚' },
  { name: '信', icon: '🔥', genre: '流行' },
  { name: '陈小春', icon: '🎤', genre: '流行' },
  { name: '林志炫', icon: '🎤', genre: '流行' },
  { name: '黄品源', icon: '🎼', genre: '流行' },
  { name: '张震岳', icon: '🎸', genre: '流行' },
  { name: '范逸臣', icon: '🎤', genre: '流行' },
  { name: '吴克群', icon: '🎹', genre: '流行' },
  { name: '李玉刚', icon: '🎭', genre: '民族' },
  { name: '霍尊', icon: '🎵', genre: '民族' },
  { name: '李宗盛', icon: '🎸', genre: '经典' },
  { name: '罗志祥', icon: '💃', genre: '流行' },
  { name: '孙楠', icon: '🎤', genre: '流行' },
  { name: '韩磊', icon: '👑', genre: '流行' },
  { name: '沙宝亮', icon: '🎵', genre: '流行' },
  { name: '满文军', icon: '🎤', genre: '流行' },
  { name: '庞龙', icon: '🎵', genre: '流行' },
  { name: '刀郎', icon: '🎸', genre: '民谣' },
  { name: '腾格尔', icon: '🎵', genre: '民族' },
  { name: '阿宝', icon: '🎤', genre: '民族' },
  { name: '吕方', icon: '🎤', genre: '经典' },
  { name: '巫启贤', icon: '🎵', genre: '流行' },
  { name: '童安格', icon: '🎸', genre: '经典' },
  { name: '姜育恒', icon: '🎤', genre: '经典' },
  { name: '费翔', icon: '🌟', genre: '经典' },
  { name: '屠洪刚', icon: '🎵', genre: '流行' },
  { name: '毛宁', icon: '🎤', genre: '流行' },
  { name: '林依轮', icon: '🎵', genre: '流行' },
  { name: '解晓东', icon: '🎤', genre: '流行' },
  { name: '邰正宵', icon: '🎵', genre: '流行' },
  { name: '林子祥', icon: '🎸', genre: '经典' },
  { name: '张明敏', icon: '🎵', genre: '经典' },
  { name: '蔡国庆', icon: '🎤', genre: '流行' },
  { name: '阎维文', icon: '👑', genre: '民族' },
  { name: '戴玉强', icon: '🎵', genre: '民族' },
  { name: '廖昌永', icon: '🎤', genre: '民族' },
  { name: '莫华伦', icon: '🎵', genre: '民族' },
  { name: '刘欢', icon: '👑', genre: '流行' },
  { name: '郑智化', icon: '🎸', genre: '流行' },
  { name: '黄大炜', icon: '🎵', genre: '流行' },
  { name: '李泉', icon: '🎹', genre: '流行' },
  { name: '陈楚生', icon: '🎸', genre: '流行' },
  { name: '苏醒', icon: '🎤', genre: '流行' },
  { name: '魏晨', icon: '🎵', genre: '流行' },
  { name: '俞灏明', icon: '🎤', genre: '流行' },
  { name: '陆虎', icon: '🎵', genre: '流行' },
  { name: '黄致列', icon: '🎤', genre: '流行' },
  { name: '迪玛希', icon: '🌟', genre: '流行' },

  // === 华语说唱/R&B男歌手（50位） ===
  { name: 'GAI', icon: '🔥', genre: '说唱' },
  { name: '潘玮柏', icon: '🎤', genre: '说唱' },
  { name: '黄明志', icon: '🎤', genre: '说唱' },
  { name: '方大同', icon: '🎵', genre: 'R&B' },
  { name: 'MC HotDog', icon: '🔥', genre: '说唱' },
  { name: '大支', icon: '🎤', genre: '说唱' },
  { name: 'TizzyT', icon: '🎧', genre: '说唱' },
  { name: '那吾克热', icon: '🎵', genre: '说唱' },
  { name: 'Jony J', icon: '🎤', genre: '说唱' },
  { name: 'PG ONE', icon: '🎵', genre: '说唱' },
  { name: 'Bridge', icon: '🎤', genre: '说唱' },
  { name: 'ICE', icon: '🎵', genre: '说唱' },
  { name: 'Ty', icon: '🎤', genre: '说唱' },
  { name: 'AR', icon: '🎵', genre: '说唱' },
  { name: 'D-evil', icon: '🎤', genre: '说唱' },
  { name: 'YoungG', icon: '🎵', genre: '说唱' },
  { name: 'Key.L', icon: '🎤', genre: '说唱' },
  { name: 'TT', icon: '🎵', genre: '说唱' },
  { name: '功夫胖', icon: '🎤', genre: '说唱' },
  { name: '艾热', icon: '🎵', genre: '说唱' },
  { name: '李佳隆', icon: '🎤', genre: '说唱' },
  { name: '小青龙', icon: '🎵', genre: '说唱' },
  { name: '辉子', icon: '🎤', genre: '说唱' },
  { name: '杨和苏', icon: '🎵', genre: '说唱' },
  { name: '派克特', icon: '🎤', genre: '说唱' },
  { name: '满舒克', icon: '🎵', genre: '说唱' },
  { name: '刘聪', icon: '🎤', genre: '说唱' },
  { name: '法老', icon: '🎵', genre: '说唱' },
  { name: '幼稚园杀手', icon: '🎤', genre: '说唱' },
  { name: '马俊', icon: '🎵', genre: '说唱' },
  { name: 'J.Sheon', icon: '🎤', genre: 'R&B' },
  { name: '韦礼安', icon: '🎵', genre: '流行' },
  { name: '李玖哲', icon: '🎤', genre: 'R&B' },
  { name: '侧田', icon: '🎵', genre: 'R&B' },
  { name: '张敬轩', icon: '🎤', genre: '流行' },
  { name: '陈伟霆', icon: '🌟', genre: '流行' },
  { name: '李圣杰', icon: '🎵', genre: '流行' },
  { name: '张栋梁', icon: '🎤', genre: '流行' },
  { name: '金志文', icon: '🎸', genre: '流行' },
  { name: '白举纲', icon: '🎵', genre: '流行' },
  { name: '平安', icon: '🎤', genre: '流行' },
  { name: '张玮', icon: '🎵', genre: '流行' },
  { name: '李代沫', icon: '🎤', genre: '流行' },
  { name: '权振东', icon: '🎵', genre: '流行' },
  { name: '李琦', icon: '🎤', genre: '流行' },
  { name: '梁博', icon: '🎸', genre: '摇滚' },
  { name: '郭顶', icon: '🎤', genre: '独立' },
  { name: '贰佰', icon: '🎸', genre: '摇滚' },
  { name: '宋冬野', icon: '🎵', genre: '民谣' },
  { name: '马頔', icon: '🎸', genre: '民谣' },

  // === 华语民谣/摇滚男歌手（50位） ===
  { name: '万晓利', icon: '🎵', genre: '民谣' },
  { name: '周云蓬', icon: '🎸', genre: '民谣' },
  { name: '小河', icon: '🎵', genre: '独立' },
  { name: '张楚', icon: '🎸', genre: '摇滚' },
  { name: '何勇', icon: '🎵', genre: '摇滚' },
  { name: '窦唯', icon: '🎸', genre: '摇滚' },
  { name: '高旗', icon: '🎵', genre: '摇滚' },
  { name: '谢天笑', icon: '🎸', genre: '摇滚' },
  { name: '左小祖咒', icon: '🎵', genre: '独立' },
  { name: '张玮玮', icon: '🎸', genre: '民谣' },
  { name: '郭龙', icon: '🎵', genre: '民谣' },
  { name: '尧十三', icon: '🎸', genre: '民谣' },
  { name: '万能青年旅店', icon: '🎵', genre: '摇滚' },
  { name: '二手玫瑰', icon: '🌹', genre: '摇滚' },
  { name: '新裤子', icon: '🎸', genre: '摇滚' },
  { name: '痛仰', icon: '🎵', genre: '摇滚' },
  { name: '刺猬', icon: '🎸', genre: '摇滚' },
  { name: '扭曲机器', icon: '🎵', genre: '摇滚' },
  { name: '旅行团', icon: '🎸', genre: '独立' },
  { name: '逃跑计划', icon: '🎵', genre: '摇滚' },
  { name: '重塑雕像的权利', icon: '🎸', genre: '独立' },
  { name: 'Joyside', icon: '🎵', genre: '摇滚' },
  { name: 'PK14', icon: '🎸', genre: '独立' },
  { name: '后海大鲨鱼', icon: '🎵', genre: '独立' },
  { name: '丢火车', icon: '🎸', genre: '独立' },
  { name: '声音玩具', icon: '🎵', genre: '独立' },
  { name: '棱镜', icon: '🎸', genre: '独立' },
  { name: 'AV大久保', icon: '🎵', genre: '独立' },
  { name: '橘子海', icon: '🎸', genre: '独立' },
  { name: 'Hyper Slash', icon: '🎵', genre: '独立' },
  { name: '鲸鱼马戏团', icon: '🎸', genre: '独立' },
  { name: '沼泽', icon: '🎵', genre: '独立' },
  { name: '达闻西', icon: '🎸', genre: '独立' },
  { name: '夜猫俱乐部', icon: '🎵', genre: '独立' },
  { name: '法兹', icon: '🎸', genre: '独立' },
  { name: 'Fine乐团', icon: '🎵', genre: '独立' },
  { name: '脆莓', icon: '🎸', genre: '独立' },
  { name: '五条人', icon: '🎵', genre: '独立' },
  { name: 'Mr.Miss', icon: '🎸', genre: '独立' },
  { name: '九连真人', icon: '🎵', genre: '民谣' },
  { name: '钱正昊', icon: '🎤', genre: '流行' },
  { name: '朱星杰', icon: '🎵', genre: '流行' },
  { name: '范丞丞', icon: '🎤', genre: '流行' },
  { name: '朱正廷', icon: '🎵', genre: '流行' },
  { name: '黄明昊', icon: '🎤', genre: '流行' },
  { name: '陈立农', icon: '🎵', genre: '流行' },
  { name: '尤长靖', icon: '🎤', genre: '流行' },
  { name: '林彦俊', icon: '🎵', genre: '流行' },
  { name: '卜凡', icon: '🎤', genre: '流行' },
  { name: '黄子韬', icon: '🎵', genre: '流行' },

  // === 华语乐队/组合（100位） ===
  { name: '五月天', icon: '🎵', genre: '摇滚' },
  { name: 'Beyond', icon: '🎸', genre: '摇滚' },
  { name: '苏打绿', icon: '🎸', genre: '独立' },
  { name: '动力火车', icon: '🔥', genre: '流行' },
  { name: '羽泉', icon: '🎤', genre: '流行' },
  { name: '凤凰传奇', icon: '🔥', genre: '流行' },
  { name: '筷子兄弟', icon: '🎵', genre: '流行' },
  { name: '水木年华', icon: '🌊', genre: '民谣' },
  { name: '纵贯线', icon: '🎸', genre: '摇滚' },
  { name: '信乐团', icon: '🎤', genre: '摇滚' },
  { name: '飞儿乐团', icon: '🎸', genre: '摇滚' },
  { name: '南拳妈妈', icon: '🎵', genre: '流行' },
  { name: '零点乐队', icon: '🎸', genre: '摇滚' },
  { name: '黑豹乐队', icon: '🎵', genre: '摇滚' },
  { name: '唐朝乐队', icon: '🎸', genre: '摇滚' },
  { name: '轮回乐队', icon: '🎵', genre: '摇滚' },
  { name: '面孔乐队', icon: '🎸', genre: '摇滚' },
  { name: '花儿乐队', icon: '🎵', genre: '摇滚' },
  { name: '玖月奇迹', icon: '🎤', genre: '流行' },
  { name: '好妹妹乐队', icon: '🎵', genre: '民谣' },
  { name: '摩登兄弟', icon: '🎸', genre: '流行' },
  { name: 'TFBOYS', icon: '🌟', genre: '流行' },
  { name: 'SNH48', icon: '🌸', genre: '流行' },
  { name: 'BonBon Girls 303', icon: '💃', genre: '流行' },
  { name: 'R1SE', icon: '🔥', genre: '流行' },
  { name: '时代少年团', icon: '👦', genre: '流行' },
  { name: 'THE9', icon: '💎', genre: '流行' },
  { name: '火箭少女101', icon: '🚀', genre: '流行' },
  { name: 'UNINE', icon: '🌟', genre: '流行' },
  { name: 'ONER', icon: '⭐', genre: '流行' },
  { name: '至上励合', icon: '🎵', genre: '流行' },
  { name: 'Top Combine', icon: '🎤', genre: '流行' },
  { name: '183Club', icon: '🎸', genre: '流行' },
  { name: '5566', icon: '🎵', genre: '流行' },
  { name: 'F4', icon: '🌟', genre: '流行' },
  { name: '小虎队', icon: '🐯', genre: '经典' },
  { name: '草蜢', icon: '🎤', genre: '经典' },
  { name: '达明一派', icon: '🎵', genre: '经典' },
  { name: '太极乐队', icon: '☯️', genre: '摇滚' },
  { name: 'Twins', icon: '👯', genre: '流行' },
  { name: '2R', icon: '🎤', genre: '流行' },
  { name: 'BY2', icon: '👯', genre: '流行' },
  { name: 'S.H.E', icon: '🌸', genre: '流行' },
  { name: 'S翼乐团', icon: '🎸', genre: '摇滚' },
  { name: '苏打绿', icon: '🌿', genre: '独立' },
  { name: '老狼', icon: '🐺', genre: '民谣' },
  { name: '野孩子', icon: '🎸', genre: '民谣' },
  { name: '房东的猫', icon: '🐱', genre: '民谣' },
  { name: '海龟先生', icon: '🐢', genre: '摇滚' },
  { name: 'Click#15', icon: '🎸', genre: '摇滚' },
  { name: 'Joker Xue', icon: '🃏', genre: '流行' },
  { name: '低苦艾', icon: '🎵', genre: '摇滚' },
  { name: '谢春花', icon: '🌸', genre: '民谣' },
  { name: '鹿先森乐队', icon: '🦌', genre: '民谣' },
  { name: '斯斯与帆', icon: '🎵', genre: '民谣' },
  { name: 'Schoolgirl Byebye', icon: '👧', genre: '独立' },
  { name: '八三夭', icon: '🎸', genre: '摇滚' },
  { name: '草东没有派对', icon: '🌿', genre: '独立' },
  { name: '茄子蛋', icon: '🍆', genre: '摇滚' },
  { name: '落日飞车', icon: '🚗', genre: '独立' },
  { name: '告五人', icon: '🎤', genre: '流行' },
  { name: '宇宙人', icon: '👽', genre: '流行' },
  { name: '五月天', icon: '🎵', genre: '摇滚' },
  { name: '滨崎步', icon: '🎤', genre: 'J-Pop' },
  { name: 'Mr.', icon: '🎸', genre: '流行' },
  { name: 'Dear Jane', icon: '🎵', genre: '流行' },
  { name: 'RubberBand', icon: '🎸', genre: '流行' },
  { name: 'Supper Moment', icon: '🎤', genre: '流行' },
  { name: 'ToNick', icon: '🎵', genre: '流行' },
  { name: 'Kolor', icon: '🎨', genre: '流行' },
  { name: 'per se', icon: '🎸', genre: '独立' },
  { name: 'Serrini', icon: '🎤', genre: '独立' },
  { name: 'Phoon', icon: '🎵', genre: '独立' },
  { name: 'Evade 飛', icon: '🎸', genre: '独立' },
  { name: 'Never Knows Tomorrow', icon: '🎤', genre: '独立' },
  { name: '杨千嬅', icon: '🌺', genre: '流行' },
  { name: '郑秀文', icon: '💃', genre: '流行' },
  { name: '容祖儿', icon: '🌸', genre: '流行' },
  { name: '陈慧琳', icon: '💎', genre: '流行' },
  { name: '梁咏琪', icon: '🎵', genre: '流行' },
  { name: '李心洁', icon: '🎤', genre: '流行' },
  { name: '梁汉文', icon: '🎵', genre: '流行' },
  { name: '许志安', icon: '🎤', genre: '流行' },
  { name: '陈晓东', icon: '🎵', genre: '流行' },
  { name: '张智霖', icon: '🎤', genre: '流行' },
  { name: '郑伊健', icon: '🎵', genre: '流行' },
  { name: '谢霆锋', icon: '🎸', genre: '摇滚' },
  { name: '陈冠希', icon: '🎤', genre: '说唱' },
  { name: '余文乐', icon: '🎵', genre: '流行' },
  { name: '房祖名', icon: '🎤', genre: '流行' },
  { name: '谢天华', icon: '🎵', genre: '流行' },
  { name: '陈浩民', icon: '🎤', genre: '流行' },
  { name: '林峯', icon: '🎵', genre: '流行' },
  { name: '吴卓羲', icon: '🎤', genre: '流行' },
  { name: '陈键锋', icon: '🎵', genre: '流行' },
  { name: '马国明', icon: '🎤', genre: '流行' },
  { name: '郑嘉颖', icon: '🎵', genre: '流行' },
  { name: '黄宗泽', icon: '🎤', genre: '流行' },

  // === 欧美男歌手（100位） ===
  { name: 'Ed Sheeran', icon: '🎸', genre: '流行' },
  { name: 'Justin Bieber', icon: '🎤', genre: '流行' },
  { name: 'Bruno Mars', icon: '🎩', genre: 'R&B' },
  { name: 'The Weeknd', icon: '🌙', genre: 'R&B' },
  { name: 'Shawn Mendes', icon: '🎸', genre: '流行' },
  { name: 'Charlie Puth', icon: '🎹', genre: '流行' },
  { name: 'Sam Smith', icon: '🎤', genre: '流行' },
  { name: 'John Legend', icon: '🎹', genre: 'R&B' },
  { name: 'Adam Levine', icon: '🎤', genre: '流行' },
  { name: 'Michael Jackson', icon: '👑', genre: '经典' },
  { name: 'Justin Timberlake', icon: '🎵', genre: '流行' },
  { name: 'Usher', icon: '🎤', genre: 'R&B' },
  { name: 'Chris Brown', icon: '🔥', genre: 'R&B' },
  { name: 'Drake', icon: '🎧', genre: '说唱' },
  { name: 'Post Malone', icon: '🎤', genre: '说唱' },
  { name: 'Travis Scott', icon: '🔥', genre: '说唱' },
  { name: 'Kendrick Lamar', icon: '👑', genre: '说唱' },
  { name: 'Eminem', icon: '🎤', genre: '说唱' },
  { name: 'Jay-Z', icon: '💎', genre: '说唱' },
  { name: 'Kanye West', icon: '🌟', genre: '说唱' },
  { name: 'Harry Styles', icon: '🎤', genre: '流行' },
  { name: 'Zayn Malik', icon: '🎵', genre: '流行' },
  { name: 'Niall Horan', icon: '🎸', genre: '流行' },
  { name: 'Louis Tomlinson', icon: '🎤', genre: '流行' },
  { name: 'Liam Payne', icon: '🎵', genre: '流行' },
  { name: 'Troye Sivan', icon: '🎤', genre: '流行' },
  { name: 'Khalid', icon: '🎵', genre: 'R&B' },
  { name: 'Lauv', icon: '🎤', genre: '流行' },
  { name: 'ZAYN', icon: '🎵', genre: 'R&B' },
  { name: 'Bebe Rexha', icon: '🎤', genre: '流行' },
  { name: 'Bazzi', icon: '🎵', genre: '流行' },
  { name: 'Calum Scott', icon: '🎤', genre: '流行' },
  { name: 'Dean Lewis', icon: '🎵', genre: '流行' },
  { name: 'Lewis Capaldi', icon: '🎤', genre: '流行' },
  { name: 'James Arthur', icon: '🎵', genre: '流行' },
  { name: 'Tom Walker', icon: '🎤', genre: '流行' },
  { name: 'Lukas Graham', icon: '🎵', genre: '流行' },
  { name: 'Machine Gun Kelly', icon: '🎸', genre: '摇滚' },
  { name: 'Travis Mills', icon: '🎤', genre: '流行' },
  { name: 'MAX', icon: '🎵', genre: '流行' },
  { name: 'HRVY', icon: '🎤', genre: '流行' },
  { name: 'Johnny Orlando', icon: '🎵', genre: '流行' },
  { name: 'Alec Benjamin', icon: '🎤', genre: '流行' },
  { name: 'Jeremy Zucker', icon: '🎵', genre: '流行' },
  { name: 'Conan Gray', icon: '🎤', genre: '流行' },
  { name: 'Jack Harlow', icon: '🎵', genre: '说唱' },
  { name: 'Lil Nas X', icon: '🤠', genre: '说唱' },
  { name: 'DaBaby', icon: '🎤', genre: '说唱' },
  { name: 'Roddy Ricch', icon: '🎵', genre: '说唱' },
  { name: 'Polo G', icon: '🎤', genre: '说唱' },
  { name: 'Pop Smoke', icon: '🎵', genre: '说唱' },
  { name: 'Juice WRLD', icon: '🎤', genre: '说唱' },
  { name: 'XXXTentacion', icon: '🎵', genre: '说唱' },
  { name: 'Lil Peep', icon: '🎤', genre: '说唱' },
  { name: 'Mac Miller', icon: '🎵', genre: '说唱' },
  { name: 'Snoop Dogg', icon: '🎤', genre: '说唱' },
  { name: 'Dr. Dre', icon: '🎵', genre: '说唱' },
  { name: '50 Cent', icon: '🎤', genre: '说唱' },
  { name: 'Nelly', icon: '🎵', genre: '说唱' },
  { name: 'Ludacris', icon: '🎤', genre: '说唱' },
  { name: 'T.I.', icon: '🎵', genre: '说唱' },
  { name: 'Lil Wayne', icon: '🎤', genre: '说唱' },
  { name: 'Nicki Minaj', icon: '👑', genre: '说唱' },
  { name: 'Cardi B', icon: '💎', genre: '说唱' },
  { name: 'Megan Thee Stallion', icon: '🔥', genre: '说唱' },
  { name: 'Doja Cat', icon: '🐱', genre: '说唱' },
  { name: 'Saweetie', icon: '💅', genre: '说唱' },
  { name: 'City Girls', icon: '👯', genre: '说唱' },
  { name: 'Rico Nasty', icon: '🎤', genre: '说唱' },
  { name: 'Princess Nokia', icon: '👸', genre: '说唱' },
  { name: 'Flo Milli', icon: '🎵', genre: '说唱' },
  { name: 'Latto', icon: '🎤', genre: '说唱' },
  { name: 'Ice Spice', icon: '🧊', genre: '说唱' },
  { name: 'GloRilla', icon: '🦍', genre: '说唱' },
  { name: 'Sexyy Red', icon: '❤️', genre: '说唱' },
  { name: 'Yung Gravy', icon: '🎵', genre: '说唱' },
  { name: 'bbno$', icon: '🎤', genre: '说唱' },
  { name: 'Yung Bae', icon: '🎵', genre: '说唱' },
  { name: 'Rich Brian', icon: '🎤', genre: '说唱' },
  { name: 'Joji', icon: '🎵', genre: 'R&B' },
  { name: 'Pink Sweat$', icon: '🎤', genre: 'R&B' },
  { name: 'Daniel Caesar', icon: '🎵', genre: 'R&B' },
  { name: 'Brent Faiyaz', icon: '🎤', genre: 'R&B' },
  { name: 'PARTYNEXTDOOR', icon: '🎵', genre: 'R&B' },
  { name: 'Bryson Tiller', icon: '🎤', genre: 'R&B' },
  { name: 'Tory Lanez', icon: '🎵', genre: 'R&B' },
  { name: '6LACK', icon: '🎤', genre: 'R&B' },
  { name: 'SZA', icon: '🎵', genre: 'R&B' },
  { name: 'H.E.R.', icon: '🎸', genre: 'R&B' },
  { name: 'Summer Walker', icon: '🎤', genre: 'R&B' },
  { name: 'Kehlani', icon: '🎵', genre: 'R&B' },
  { name: 'Jhené Aiko', icon: '🎤', genre: 'R&B' },
  { name: 'Ella Mai', icon: '🎵', genre: 'R&B' },
  { name: 'Queen Naija', icon: '👸', genre: 'R&B' },
  { name: 'Ari Lennox', icon: '🎤', genre: 'R&B' },
  { name: 'Normani', icon: '💃', genre: 'R&B' },
  { name: 'Victoria Monét', icon: '🎵', genre: 'R&B' },

  // === 日韩男歌手/男团（100位） ===
  { name: 'BIGBANG', icon: '👑', genre: 'K-Pop' },
  { name: 'EXO', icon: '🌟', genre: 'K-Pop' },
  { name: 'BTS', icon: '🔥', genre: 'K-Pop' },
  { name: 'GOT7', icon: '🎵', genre: 'K-Pop' },
  { name: 'NCT', icon: '⭐', genre: 'K-Pop' },
  { name: 'SEVENTEEN', icon: '💎', genre: 'K-Pop' },
  { name: 'Stray Kids', icon: '🎤', genre: 'K-Pop' },
  { name: 'ATEEZ', icon: '🔥', genre: 'K-Pop' },
  { name: 'TXT', icon: '🌟', genre: 'K-Pop' },
  { name: 'ENHYPEN', icon: '⭐', genre: 'K-Pop' },
  { name: 'TREASURE', icon: '💎', genre: 'K-Pop' },
  { name: 'CRAVITY', icon: '🎵', genre: 'K-Pop' },
  { name: 'THE BOYZ', icon: '👦', genre: 'K-Pop' },
  { name: 'AB6IX', icon: '🎤', genre: 'K-Pop' },
  { name: 'ONEUS', icon: '🌙', genre: 'K-Pop' },
  { name: 'ONEWE', icon: '🎸', genre: 'K-Pop' },
  { name: 'Golden Child', icon: '✨', genre: 'K-Pop' },
  { name: 'SF9', icon: '🎵', genre: 'K-Pop' },
  { name: 'PENTAGON', icon: '⭐', genre: 'K-Pop' },
  { name: 'MONSTA X', icon: '💪', genre: 'K-Pop' },
  { name: 'ASTRO', icon: '⭐', genre: 'K-Pop' },
  { name: 'iKON', icon: '👑', genre: 'K-Pop' },
  { name: 'WINNER', icon: '🏆', genre: 'K-Pop' },
  { name: 'SHINee', icon: '✨', genre: 'K-Pop' },
  { name: 'Super Junior', icon: '💙', genre: 'K-Pop' },
  { name: '2PM', icon: '🎵', genre: 'K-Pop' },
  { name: 'B1A4', icon: '🎤', genre: 'K-Pop' },
  { name: 'BTOB', icon: '💙', genre: 'K-Pop' },
  { name: 'Block B', icon: '🎵', genre: 'K-Pop' },
  { name: 'VIXX', icon: '⭐', genre: 'K-Pop' },
  { name: 'INFINITE', icon: '∞', genre: 'K-Pop' },
  { name: 'Teen Top', icon: '🔝', genre: 'K-Pop' },
  { name: 'MBLAQ', icon: '🎵', genre: 'K-Pop' },
  { name: 'ZE:A', icon: '⭐', genre: 'K-Pop' },
  { name: 'U-KISS', icon: '💋', genre: 'K-Pop' },
  { name: 'FT Island', icon: '🏝️', genre: 'K-Pop' },
  { name: 'CNBLUE', icon: '🎸', genre: 'K-Pop' },
  { name: 'N.Flying', icon: '✈️', genre: 'K-Pop' },
  { name: 'DAY6', icon: '🎵', genre: 'K-Pop' },
  { name: 'The Rose', icon: '🌹', genre: 'K-Pop' },
  { name: 'Xdinary Heroes', icon: '🎸', genre: 'K-Pop' },
  { name: 'Taeyang', icon: '☀️', genre: 'K-Pop' },
  { name: 'G-Dragon', icon: '🐉', genre: 'K-Pop' },
  { name: 'T.O.P', icon: '⭐', genre: 'K-Pop' },
  { name: 'Daesung', icon: '🎤', genre: 'K-Pop' },
  { name: 'Seungri', icon: '🎵', genre: 'K-Pop' },
  { name: 'Baekhyun', icon: '🌟', genre: 'K-Pop' },
  { name: 'Kai', icon: '🎭', genre: 'K-Pop' },
  { name: 'D.O.', icon: '🎤', genre: 'K-Pop' },
  { name: 'Chanyeol', icon: '🎸', genre: 'K-Pop' },
  { name: 'Sehun', icon: '⭐', genre: 'K-Pop' },
  { name: 'Suho', icon: '💙', genre: 'K-Pop' },
  { name: 'Chen', icon: '🎵', genre: 'K-Pop' },
  { name: 'Xiumin', icon: '❄️', genre: 'K-Pop' },
  { name: 'Lay', icon: '🦄', genre: 'K-Pop' },
  { name: 'Jungkook', icon: '🐰', genre: 'K-Pop' },
  { name: 'Jimin', icon: '🦋', genre: 'K-Pop' },
  { name: 'V', icon: '🐯', genre: 'K-Pop' },
  { name: 'RM', icon: '🎤', genre: 'K-Pop' },
  { name: 'Jin', icon: '💜', genre: 'K-Pop' },
  { name: 'Suga', icon: '🎹', genre: 'K-Pop' },
  { name: 'J-Hope', icon: '☀️', genre: 'K-Pop' },
  { name: '米津玄师', icon: '🎵', genre: 'J-Pop' },
  { name: 'RADWIMPS', icon: '🎸', genre: 'J-Pop' },
  { name: 'ONE OK ROCK', icon: '🎸', genre: 'J-Rock' },
  { name: 'King Gnu', icon: '👑', genre: 'J-Pop' },
  { name: 'Official髭男dism', icon: '🎵', genre: 'J-Pop' },
  { name: 'back number', icon: '🎸', genre: 'J-Pop' },
  { name: '[Alexandros]', icon: '🎵', genre: 'J-Rock' },
  { name: 'BUMP OF CHICKEN', icon: '🐔', genre: 'J-Rock' },
  { name: 'UVERworld', icon: '🎸', genre: 'J-Rock' },
  { name: 'MAN WITH A MISSION', icon: '🐺', genre: 'J-Rock' },
  { name: 'THE ORAL CIGARETTES', icon: '🎸', genre: 'J-Rock' },
  { name: 'Mrs. GREEN APPLE', icon: '🍏', genre: 'J-Pop' },
  { name: 'WANIMA', icon: '🎵', genre: 'J-Rock' },
  { name: 'Suchmos', icon: '🎸', genre: 'J-Pop' },
  { name: 'Vaundy', icon: '🎵', genre: 'J-Pop' },
  { name: 'Ado', icon: '🎤', genre: 'J-Pop' },
  { name: 'YOASOBI', icon: '✨', genre: 'J-Pop' },
  { name: 'Kenshi Yonezu', icon: '🎵', genre: 'J-Pop' },
  { name: 'Aimer', icon: '🎤', genre: 'J-Pop' },
  { name: 'LiSA', icon: '🔥', genre: 'J-Pop' },
  { name: '嵐', icon: '🌪️', genre: 'J-Pop' },
  { name: 'KAT-TUN', icon: '⭐', genre: 'J-Pop' },
  { name: 'NEWS', icon: '📰', genre: 'J-Pop' },
  { name: 'Kis-My-Ft2', icon: '🎵', genre: 'J-Pop' },
  { name: 'Hey! Say! JUMP', icon: '🎤', genre: 'J-Pop' },
  { name: 'King & Prince', icon: '👑', genre: 'J-Pop' },
  { name: 'SixTONES', icon: '⭐', genre: 'J-Pop' },
  { name: 'Snow Man', icon: '❄️', genre: 'J-Pop' },
  { name: 'EXILE', icon: '🎵', genre: 'J-Pop' },
  { name: '三代目 J Soul Brothers', icon: '🎤', genre: 'J-Pop' },
  { name: 'GENERATIONS', icon: '🌟', genre: 'J-Pop' },
  { name: 'THE RAMPAGE', icon: '🔥', genre: 'J-Pop' },
  { name: 'FANTASTICS', icon: '✨', genre: 'J-Pop' },
  { name: 'DA PUMP', icon: '💃', genre: 'J-Pop' },
  { name: 'w-inds.', icon: '🌪️', genre: 'J-Pop' },
  { name: 'Lead', icon: '🎵', genre: 'J-Pop' },
];

export const FEMALE_ARTISTS = [
  // === 华语顶级女歌手（100位） ===
  { name: '邓紫棋', icon: '🎵', genre: '流行' },
  { name: '王菲', icon: '💎', genre: '经典' },
  { name: '孙燕姿', icon: '🌟', genre: '流行' },
  { name: '蔡依林', icon: '💃', genre: '流行' },
  { name: '李宇春', icon: '👸', genre: '流行' },
  { name: '张靓颖', icon: '🌟', genre: '流行' },
  { name: '那英', icon: '👑', genre: '流行' },
  { name: '韩红', icon: '🎤', genre: '流行' },
  { name: '田馥甄', icon: '🌺', genre: '流行' },
  { name: '梁静茹', icon: '💝', genre: '流行' },
  { name: '张碧晨', icon: '🦋', genre: '流行' },
  { name: '郁可唯', icon: '🌺', genre: '流行' },
  { name: '谭维维', icon: '🔥', genre: '流行' },
  { name: '袁娅维', icon: '🎤', genre: '流行' },
  { name: '张韶涵', icon: '🎀', genre: '流行' },
  { name: '徐佳莹', icon: '🎹', genre: '流行' },
  { name: '杨丞琳', icon: '🌺', genre: '流行' },
  { name: 'A-Lin', icon: '🌟', genre: '流行' },
  { name: '丁当', icon: '🔥', genre: '流行' },
  { name: '彭佳慧', icon: '💪', genre: '流行' },
  { name: '陈粒', icon: '🌙', genre: '民谣' },
  { name: '花粥', icon: '🌸', genre: '民谣' },
  { name: '程璧', icon: '🎸', genre: '民谣' },
  { name: '邓丽君', icon: '👑', genre: '经典' },
  { name: '莫文蔚', icon: '💫', genre: '流行' },
  { name: '张惠妹', icon: '👸', genre: '流行' },
  { name: '容祖儿', icon: '🌸', genre: '流行' },
  { name: '杨千嬅', icon: '🌺', genre: '流行' },
  { name: '郑秀文', icon: '💃', genre: '流行' },
  { name: '梁咏琪', icon: '🎵', genre: '流行' },
  { name: '陈慧琳', icon: '💎', genre: '流行' },
  { name: '林忆莲', icon: '💫', genre: '流行' },
  { name: '王心凌', icon: '💝', genre: '流行' },
  { name: '萧亚轩', icon: '🎵', genre: '流行' },
  { name: '许茹芸', icon: '🌺', genre: '流行' },
  { name: '张艾嘉', icon: '🌟', genre: '经典' },
  { name: '叶倩文', icon: '👑', genre: '经典' },
  { name: '刘若英', icon: '💫', genre: '流行' },
  { name: '范玮琪', icon: '🌸', genre: '流行' },
  { name: '陈绮贞', icon: '🎸', genre: '独立' },
  { name: '戴佩妮', icon: '🎵', genre: '流行' },
  { name: '梁文音', icon: '🎤', genre: '流行' },
  { name: '郭静', icon: '🌸', genre: '流行' },
  { name: '周蕙', icon: '🌺', genre: '流行' },
  { name: '辛晓琪', icon: '💝', genre: '流行' },
  { name: '苏慧伦', icon: '🌸', genre: '流行' },
  { name: '范晓萱', icon: '🎀', genre: '流行' },
  { name: '卢巧音', icon: '🎵', genre: '流行' },
  { name: '李玟', icon: '💃', genre: '流行' },
  { name: '黄小琥', icon: '👸', genre: '流行' },
  { name: '许慧欣', icon: '🎤', genre: '流行' },
  { name: '陈嘉桦', icon: '💪', genre: '流行' },
  { name: '孙盛希', icon: '🌟', genre: '流行' },
  { name: '魏如萱', icon: '🎵', genre: '独立' },
  { name: '徐若瑄', icon: '🌺', genre: '流行' },
  { name: '江美琪', icon: '🎵', genre: '流行' },
  { name: '张惠春', icon: '🎵', genre: '流行' },
  { name: '金池', icon: '🎤', genre: '流行' },
  { name: '黄绮珊', icon: '🎵', genre: '流行' },
  { name: '单依纯', icon: '🎤', genre: '流行' },
  { name: '刘惜君', icon: '🎵', genre: '流行' },
  { name: '任然', icon: '🎤', genre: '流行' },
  { name: '花僮', icon: '🎵', genre: '流行' },
  { name: '孟庭苇', icon: '🌺', genre: '经典' },
  { name: '高胜美', icon: '🎵', genre: '经典' },
  { name: '杨钰莹', icon: '🌸', genre: '流行' },
  { name: '毛阿敏', icon: '🎤', genre: '流行' },
  { name: '李玲玉', icon: '🎵', genre: '流行' },
  { name: '陈明', icon: '🌺', genre: '流行' },
  { name: '朱桦', icon: '🎤', genre: '流行' },
  { name: '田震', icon: '🔥', genre: '流行' },
  { name: '孙悦', icon: '🎵', genre: '流行' },
  { name: '李娜', icon: '🎤', genre: '流行' },
  { name: '艾敬', icon: '🎵', genre: '流行' },
  { name: '万芳', icon: '🎤', genre: '流行' },
  { name: '潘美辰', icon: '🌺', genre: '流行' },
  { name: '黄莺莺', icon: '🎤', genre: '经典' },
  { name: '凤飞飞', icon: '🎵', genre: '经典' },
  { name: '甄妮', icon: '🌺', genre: '经典' },
  { name: '汪明荃', icon: '🎤', genre: '经典' },
  { name: '徐小凤', icon: '🎵', genre: '经典' },
  { name: '叶丽仪', icon: '🌺', genre: '经典' },
  { name: '陈慧娴', icon: '🎤', genre: '经典' },
  { name: '关淑怡', icon: '🎵', genre: '经典' },
  { name: '彭羚', icon: '🌺', genre: '流行' },
  { name: '李蕙敏', icon: '🎤', genre: '流行' },
  { name: '李心洁', icon: '🎵', genre: '流行' },
  { name: '吉克隽逸', icon: '🔥', genre: '流行' },
  { name: '黄英', icon: '🎤', genre: '流行' },
  { name: '江映蓉', icon: '🎵', genre: '流行' },
  { name: '李霄云', icon: '🎤', genre: '流行' },
  { name: '段林希', icon: '🎵', genre: '流行' },
  { name: '刘力扬', icon: '🎤', genre: '流行' },
  { name: '尚雯婕', icon: '🎵', genre: '流行' },
  { name: '曾轶可', icon: '🎤', genre: '流行' },
  { name: '周笔畅', icon: '🎵', genre: '流行' },
  { name: '何洁', icon: '🎤', genre: '流行' },
  { name: '纪敏佳', icon: '🎵', genre: '流行' },
  { name: '黄雅莉', icon: '🎤', genre: '流行' },
  { name: '厉娜', icon: '🎵', genre: '流行' },

  // === 华语女团/组合（50位） ===
  { name: 'S.H.E', icon: '🌸', genre: '流行' },
  { name: 'Twins', icon: '👯', genre: '流行' },
  { name: 'BY2', icon: '👯', genre: '流行' },
  { name: '2R', icon: '🎤', genre: '流行' },
  { name: '飞儿乐团', icon: '🎸', genre: '摇滚' },
  { name: 'SNH48', icon: '🌸', genre: '流行' },
  { name: 'BonBon Girls 303', icon: '💃', genre: '流行' },
  { name: 'THE9', icon: '💎', genre: '流行' },
  { name: '火箭少女101', icon: '🚀', genre: '流行' },
  { name: '蜜蜂少女队', icon: '🐝', genre: '流行' },
  { name: 'AKB48 Team SH', icon: '🌸', genre: '流行' },
  { name: 'BEJ48', icon: '🌸', genre: '流行' },
  { name: 'GNZ48', icon: '🌸', genre: '流行' },
  { name: 'SHY48', icon: '🌸', genre: '流行' },
  { name: 'CKG48', icon: '🌸', genre: '流行' },
  { name: 'SING女团', icon: '🎤', genre: '流行' },
  { name: 'sunshine', icon: '☀️', genre: '流行' },
  { name: '1931女子偶像组合', icon: '👯', genre: '流行' },
  { name: 'HO2', icon: '💃', genre: '流行' },
  { name: '七朵组合', icon: '🌸', genre: '流行' },
  { name: 'Lunar', icon: '🌙', genre: '流行' },
  { name: 'M-Girls', icon: '👧', genre: '流行' },
  { name: '女子十二乐坊', icon: '🎵', genre: '民族' },
  { name: '玫瑰之约', icon: '🌹', genre: '流行' },
  { name: 'Ladybees', icon: '🐝', genre: '流行' },
  { name: '红孩儿', icon: '👧', genre: '流行' },
  { name: '吴宣仪', icon: '🌸', genre: '流行' },
  { name: '孟美岐', icon: '💎', genre: '流行' },
  { name: '杨超越', icon: '🌟', genre: '流行' },
  { name: '程潇', icon: '✨', genre: '流行' },
  { name: '鞠婧祎', icon: '🌺', genre: '流行' },
  { name: '李艺彤', icon: '🎤', genre: '流行' },
  { name: '黄婷婷', icon: '🎵', genre: '流行' },
  { name: '冯提莫', icon: '🎤', genre: '流行' },
  { name: '周淑怡', icon: '🎵', genre: '流行' },
  { name: '祝晓晗', icon: '🎤', genre: '流行' },
  { name: '蒋雪儿', icon: '🎵', genre: '流行' },
  { name: '小潘潘', icon: '🎤', genre: '流行' },
  { name: '林明祯', icon: '🎵', genre: '流行' },
  { name: '庄心妍', icon: '🎤', genre: '流行' },
  { name: '云朵', icon: '☁️', genre: '民族' },
  { name: '乌兰图雅', icon: '🎵', genre: '民族' },
  { name: '乌兰托娅', icon: '🎤', genre: '民族' },
  { name: '阿鲁阿卓', icon: '🎵', genre: '民族' },
  { name: '降央卓玛', icon: '🎤', genre: '民族' },
  { name: '德德玛', icon: '🎵', genre: '民族' },
  { name: '谭晶', icon: '🎤', genre: '民族' },
  { name: '雷佳', icon: '🎵', genre: '民族' },
  { name: '宋祖英', icon: '🎤', genre: '民族' },
  { name: '董文华', icon: '🎵', genre: '民族' },

  // === 欧美女歌手（100位） ===
  { name: 'Taylor Swift', icon: '👸', genre: '流行' },
  { name: 'Ariana Grande', icon: '🎤', genre: '流行' },
  { name: 'Billie Eilish', icon: '🌙', genre: '流行' },
  { name: 'Dua Lipa', icon: '💃', genre: '流行' },
  { name: 'Selena Gomez', icon: '🌟', genre: '流行' },
  { name: 'Demi Lovato', icon: '🎤', genre: '流行' },
  { name: 'Miley Cyrus', icon: '🔥', genre: '流行' },
  { name: 'Katy Perry', icon: '🎵', genre: '流行' },
  { name: 'Rihanna', icon: '💎', genre: 'R&B' },
  { name: 'Beyoncé', icon: '👑', genre: 'R&B' },
  { name: 'Lady Gaga', icon: '🎭', genre: '流行' },
  { name: 'Adele', icon: '🎤', genre: '流行' },
  { name: 'Sia', icon: '🎵', genre: '流行' },
  { name: 'Halsey', icon: '🌙', genre: '流行' },
  { name: 'Camila Cabello', icon: '🎤', genre: '流行' },
  { name: 'Lana Del Rey', icon: '🌹', genre: '独立' },
  { name: 'Lorde', icon: '👑', genre: '独立' },
  { name: 'SZA', icon: '🎵', genre: 'R&B' },
  { name: 'H.E.R.', icon: '🎸', genre: 'R&B' },
  { name: 'Summer Walker', icon: '🎤', genre: 'R&B' },
  { name: 'Kehlani', icon: '🎵', genre: 'R&B' },
  { name: 'Jhené Aiko', icon: '🎤', genre: 'R&B' },
  { name: 'Ella Mai', icon: '🎵', genre: 'R&B' },
  { name: 'Queen Naija', icon: '👸', genre: 'R&B' },
  { name: 'Ari Lennox', icon: '🎤', genre: 'R&B' },
  { name: 'Normani', icon: '💃', genre: 'R&B' },
  { name: 'Victoria Monét', icon: '🎵', genre: 'R&B' },
  { name: 'Nicki Minaj', icon: '👑', genre: '说唱' },
  { name: 'Cardi B', icon: '💎', genre: '说唱' },
  { name: 'Megan Thee Stallion', icon: '🔥', genre: '说唱' },
  { name: 'Doja Cat', icon: '🐱', genre: '说唱' },
  { name: 'Saweetie', icon: '💅', genre: '说唱' },
  { name: 'City Girls', icon: '👯', genre: '说唱' },
  { name: 'Rico Nasty', icon: '🎤', genre: '说唱' },
  { name: 'Princess Nokia', icon: '👸', genre: '说唱' },
  { name: 'Flo Milli', icon: '🎵', genre: '说唱' },
  { name: 'Latto', icon: '🎤', genre: '说唱' },
  { name: 'Ice Spice', icon: '🧊', genre: '说唱' },
  { name: 'GloRilla', icon: '🦍', genre: '说唱' },
  { name: 'Sexyy Red', icon: '❤️', genre: '说唱' },
  { name: 'Olivia Rodrigo', icon: '💜', genre: '流行' },
  { name: 'Sabrina Carpenter', icon: '🎤', genre: '流行' },
  { name: 'Madison Beer', icon: '🎵', genre: '流行' },
  { name: 'Tate McRae', icon: '💃', genre: '流行' },
  { name: 'Conan Gray', icon: '🎤', genre: '流行' },
  { name: 'GAYLE', icon: '🎵', genre: '流行' },
  { name: 'Gracie Abrams', icon: '🎤', genre: '流行' },
  { name: 'Maisie Peters', icon: '🎵', genre: '流行' },
  { name: 'Reneé Rapp', icon: '🎤', genre: '流行' },
  { name: 'Chappell Roan', icon: '🎵', genre: '流行' },
  { name: 'Melanie Martinez', icon: '🎤', genre: '独立' },
  { name: 'Clairo', icon: '🎵', genre: '独立' },
  { name: 'girl in red', icon: '❤️', genre: '独立' },
  { name: 'beabadoobee', icon: '🎸', genre: '独立' },
  { name: 'Arlo Parks', icon: '🎤', genre: '独立' },
  { name: 'Phoebe Bridgers', icon: '🎵', genre: '独立' },
  { name: 'Lucy Dacus', icon: '🎸', genre: '独立' },
  { name: 'Julien Baker', icon: '🎤', genre: '独立' },
  { name: 'boygenius', icon: '🎵', genre: '独立' },
  { name: 'Mitski', icon: '🎸', genre: '独立' },
  { name: 'Japanese Breakfast', icon: '🎤', genre: '独立' },
  { name: 'Soccer Mommy', icon: '🎵', genre: '独立' },
  { name: 'Snail Mail', icon: '🎸', genre: '独立' },
  { name: 'Courtney Barnett', icon: '🎤', genre: '独立' },
  { name: 'St. Vincent', icon: '🎵', genre: '独立' },
  { name: 'FKA twigs', icon: '🎸', genre: '独立' },
  { name: 'Florence Welch', icon: '🎤', genre: '独立' },
  { name: 'Marina', icon: '🎵', genre: '流行' },
  { name: 'Charli XCX', icon: '💎', genre: '流行' },
  { name: 'Kim Petras', icon: '🎤', genre: '流行' },
  { name: 'Ava Max', icon: '🎵', genre: '流行' },
  { name: 'Bebe Rexha', icon: '🎤', genre: '流行' },
  { name: 'Anne-Marie', icon: '🎵', genre: '流行' },
  { name: 'Zara Larsson', icon: '🎤', genre: '流行' },
  { name: 'Tones and I', icon: '🎵', genre: '流行' },
  { name: 'Sigrid', icon: '🎤', genre: '流行' },
  { name: 'Jorja Smith', icon: '🎵', genre: 'R&B' },
  { name: 'Mahalia', icon: '🎤', genre: 'R&B' },
  { name: 'Kiana Ledé', icon: '🎵', genre: 'R&B' },
  { name: 'Jessie Reyez', icon: '🎤', genre: 'R&B' },
  { name: 'Sabrina Claudio', icon: '🎵', genre: 'R&B' },
  { name: 'Tinashe', icon: '💃', genre: 'R&B' },
  { name: 'JoJo', icon: '🎤', genre: 'R&B' },
  { name: 'Alicia Keys', icon: '🎹', genre: 'R&B' },
  { name: 'Mary J. Blige', icon: '👑', genre: 'R&B' },
  { name: 'Christina Aguilera', icon: '🎤', genre: '流行' },
  { name: 'Britney Spears', icon: '💃', genre: '流行' },
  { name: 'Jennifer Lopez', icon: '💎', genre: '流行' },
  { name: 'Shakira', icon: '🔥', genre: '流行' },
  { name: 'Madonna', icon: '👑', genre: '经典' },
  { name: 'Whitney Houston', icon: '💫', genre: '经典' },
  { name: 'Mariah Carey', icon: '🦋', genre: '经典' },
  { name: 'Celine Dion', icon: '💝', genre: '经典' },
  { name: 'Shania Twain', icon: '🤠', genre: '乡村' },
  { name: 'Dolly Parton', icon: '👸', genre: '乡村' },
  { name: 'Carrie Underwood', icon: '🎤', genre: '乡村' },
  { name: 'Miranda Lambert', icon: '🎵', genre: '乡村' },
  { name: 'Kacey Musgraves', icon: '🌟', genre: '乡村' },
  { name: 'Maren Morris', icon: '🎤', genre: '乡村' },

  // === 日韩女歌手/女团（150位） ===
  { name: 'BLACKPINK', icon: '🖤', genre: 'K-Pop' },
  { name: 'TWICE', icon: '💖', genre: 'K-Pop' },
  { name: 'Red Velvet', icon: '❤️', genre: 'K-Pop' },
  { name: 'ITZY', icon: '✨', genre: 'K-Pop' },
  { name: 'aespa', icon: '🌟', genre: 'K-Pop' },
  { name: 'IVE', icon: '💎', genre: 'K-Pop' },
  { name: 'NewJeans', icon: '👖', genre: 'K-Pop' },
  { name: 'LE SSERAFIM', icon: '🔥', genre: 'K-Pop' },
  { name: '(G)I-DLE', icon: '👑', genre: 'K-Pop' },
  { name: 'NMIXX', icon: '🎵', genre: 'K-Pop' },
  { name: 'Kep1er', icon: '⭐', genre: 'K-Pop' },
  { name: 'STAYC', icon: '🌸', genre: 'K-Pop' },
  { name: 'Billlie', icon: '🎤', genre: 'K-Pop' },
  { name: 'Dreamcatcher', icon: '🌙', genre: 'K-Pop' },
  { name: 'Everglow', icon: '✨', genre: 'K-Pop' },
  { name: 'WJSN', icon: '🌟', genre: 'K-Pop' },
  { name: 'Oh My Girl', icon: '🌺', genre: 'K-Pop' },
  { name: 'fromis_9', icon: '🎵', genre: 'K-Pop' },
  { name: 'Brave Girls', icon: '💪', genre: 'K-Pop' },
  { name: 'VIVIZ', icon: '🌸', genre: 'K-Pop' },
  { name: 'LOONA', icon: '🌙', genre: 'K-Pop' },
  { name: 'Cherry Bullet', icon: '🍒', genre: 'K-Pop' },
  { name: 'Weeekly', icon: '🎵', genre: 'K-Pop' },
  { name: 'Rocket Punch', icon: '🚀', genre: 'K-Pop' },
  { name: 'cignature', icon: '✍️', genre: 'K-Pop' },
  { name: 'Purple Kiss', icon: '💜', genre: 'K-Pop' },
  { name: 'Pixy', icon: '🧚', genre: 'K-Pop' },
  { name: 'Secret Number', icon: '🔢', genre: 'K-Pop' },
  { name: 'woo!ah!', icon: '🎵', genre: 'K-Pop' },
  { name: 'LIGHTSUM', icon: '💡', genre: 'K-Pop' },
  { name: 'IU', icon: '💜', genre: 'K-Pop' },
  { name: 'Taeyeon', icon: '🎤', genre: 'K-Pop' },
  { name: 'Rosé', icon: '🌹', genre: 'K-Pop' },
  { name: 'Lisa', icon: '💃', genre: 'K-Pop' },
  { name: 'Jennie', icon: '💎', genre: 'K-Pop' },
  { name: 'Jisoo', icon: '🌺', genre: 'K-Pop' },
  { name: 'Sunmi', icon: '🎵', genre: 'K-Pop' },
  { name: 'Chungha', icon: '💃', genre: 'K-Pop' },
  { name: 'HyunA', icon: '🔥', genre: 'K-Pop' },
  { name: 'DAWN', icon: '🌅', genre: 'K-Pop' },
  { name: 'Jessi', icon: '👑', genre: 'K-Pop' },
  { name: 'Hwasa', icon: '🎤', genre: 'K-Pop' },
  { name: 'Wheein', icon: '🎵', genre: 'K-Pop' },
  { name: 'Solar', icon: '☀️', genre: 'K-Pop' },
  { name: 'Moonbyul', icon: '🌙', genre: 'K-Pop' },
  { name: 'Wendy', icon: '🎤', genre: 'K-Pop' },
  { name: 'Joy', icon: '🎵', genre: 'K-Pop' },
  { name: 'Seulgi', icon: '🎤', genre: 'K-Pop' },
  { name: 'Irene', icon: '💎', genre: 'K-Pop' },
  { name: 'Yeri', icon: '🎵', genre: 'K-Pop' },
  { name: 'Aimer', icon: '🎵', genre: 'J-Pop' },
  { name: 'LiSA', icon: '🔥', genre: 'J-Pop' },
  { name: 'YOASOBI', icon: '✨', genre: 'J-Pop' },
  { name: 'Ado', icon: '🎤', genre: 'J-Pop' },
  { name: '中島美嘉', icon: '🌙', genre: 'J-Pop' },
  { name: '宇多田ヒカル', icon: '🎵', genre: 'J-Pop' },
  { name: '浜崎あゆみ', icon: '👑', genre: 'J-Pop' },
  { name: '倉木麻衣', icon: '🎤', genre: 'J-Pop' },
  { name: '大塚愛', icon: '💝', genre: 'J-Pop' },
  { name: 'MISIA', icon: '🎵', genre: 'J-Pop' },
  { name: '椎名林檎', icon: '🍎', genre: 'J-Rock' },
  { name: 'あいみょん', icon: '🎸', genre: 'J-Pop' },
  { name: 'milet', icon: '🎤', genre: 'J-Pop' },
  { name: '藤井風', icon: '🎹', genre: 'J-Pop' },
  { name: 'Eve', icon: '🎵', genre: 'J-Pop' },
  { name: 'YOASOBI', icon: '✨', genre: 'J-Pop' },
  { name: 'ずっと真夜中でいいのに。', icon: '🌙', genre: 'J-Pop' },
  { name: 'ヨルシカ', icon: '🌃', genre: 'J-Pop' },
  { name: 'TUYU', icon: '🎵', genre: 'J-Pop' },
  { name: 'きのこ帝国', icon: '🍄', genre: 'J-Rock' },
  { name: 'ねごと', icon: '🎸', genre: 'J-Rock' },
  { name: 'SHISHAMO', icon: '🎵', genre: 'J-Rock' },
  { name: 'Hump Back', icon: '🎸', genre: 'J-Rock' },
  { name: 'キュウソネコカミ', icon: '🐱', genre: 'J-Rock' },
  { name: 'ゲスの極み乙女。', icon: '🎵', genre: 'J-Pop' },
  { name: 'Perfume', icon: '💎', genre: 'J-Pop' },
  { name: 'Babymetal', icon: '🤘', genre: 'J-Metal' },
  { name: 'AKB48', icon: '🌸', genre: 'J-Pop' },
  { name: 'SKE48', icon: '🌸', genre: 'J-Pop' },
  { name: 'NMB48', icon: '🌸', genre: 'J-Pop' },
  { name: 'HKT48', icon: '🌸', genre: 'J-Pop' },
  { name: 'NGT48', icon: '🌸', genre: 'J-Pop' },
  { name: '乃木坂46', icon: '🌸', genre: 'J-Pop' },
  { name: '欅坂46', icon: '🌸', genre: 'J-Pop' },
  { name: '日向坂46', icon: '🌸', genre: 'J-Pop' },
  { name: '櫻坂46', icon: '🌸', genre: 'J-Pop' },
  { name: 'モーニング娘。', icon: '🌅', genre: 'J-Pop' },
  { name: 'Juice=Juice', icon: '🍊', genre: 'J-Pop' },
  { name: 'アンジュルム', icon: '🎵', genre: 'J-Pop' },
  { name: 'つばきファクトリー', icon: '🌸', genre: 'J-Pop' },
  { name: 'BEYOOOOONDS', icon: '🎤', genre: 'J-Pop' },
  { name: 'Girls²', icon: '👧', genre: 'J-Pop' },
  { name: 'JO1', icon: '🌟', genre: 'J-Pop' },
  { name: 'INI', icon: '⭐', genre: 'J-Pop' },
  { name: 'BE:FIRST', icon: '🔥', genre: 'J-Pop' },
  { name: 'OCTPATH', icon: '🎵', genre: 'J-Pop' },
];

// 总数统计：男歌手约600+，女歌手约500+，总计1100+位
